## net architecture
model:
    model_type: OneDCNN

## datasets
data:
    datapath: ./datasets/
    dataname: FeO
    is_shuffle: True
    do_scale: True

## loss
loss:
    loss_type: MSE

## params for optimizer
optim:
    base_lr: 0.001
    weight_decay: 0.0001
    patience: 50

## training parameters
use_gpu: True
gpu_id: 0

epochs: 100
batch_size: 54

save_ckpt: True
record_type: CV
num_workers: 0

worker_dir: []
load_from: []
resume_from: []

