model:
  model_type: OneDCNN
data:
  datapath: ./datasets/
  dataname: FeO
  is_shuffle: true
  do_scale: true
loss:
  loss_type: MSE
optim:
  base_lr: 0.001
  weight_decay: 0.0001
  patience: 50
use_gpu: true
gpu_id: 0
epochs: 100
batch_size: 54
save_ckpt: true
record_type: CV
num_workers: 0
worker_dir: []
load_from: []
resume_from: []
